# AUTOGENERATED! DO NOT EDIT! File to edit: ../../modules/07_optimizers/optimizers.ipynb.

# %% auto #0
__all__ = ['rng', 'DEFAULT_LEARNING_RATE_SGD', 'DEFAULT_LEARNING_RATE_ADAM', 'DEFAULT_MOMENTUM', 'DEFAULT_BETA1', 'DEFAULT_BETA2',
           'DEFAULT_EPS', 'DEFAULT_WEIGHT_DECAY_ADAMW', 'Optimizer', 'SGD', 'Adam', 'AdamW']

# %% ../../modules/07_optimizers/optimizers.ipynb #b9e8e352
import numpy as np
rng = np.random.default_rng(42)
from typing import List, Union, Optional, Dict, Any

# Import Tensor from Module 01 (now with gradient support from Module 06)
from .tensor import Tensor

# Enable autograd to add gradient tracking to Tensor
# This module depends on Module 06 (Autograd) being available
from .autograd import enable_autograd
enable_autograd()

# Constants for optimizer defaults
DEFAULT_LEARNING_RATE_SGD = 0.01  # Default learning rate for SGD
DEFAULT_LEARNING_RATE_ADAM = 0.001  # Default learning rate for Adam/AdamW
DEFAULT_MOMENTUM = 0.9  # Default momentum for SGD
DEFAULT_BETA1 = 0.9  # First moment decay rate for Adam
DEFAULT_BETA2 = 0.999  # Second moment decay rate for Adam
DEFAULT_EPS = 1e-8  # Small epsilon for numerical stability in Adam
DEFAULT_WEIGHT_DECAY_ADAMW = 0.01  # Default weight decay for AdamW

# %% ../../modules/07_optimizers/optimizers.ipynb #9deb85eb
class Optimizer:
    """
    Base class for all optimizers.

    This class defines the common interface that all optimizers must implement:
    - zero_grad(): Clear gradients from parameters
    - step(): Update parameters based on gradients
    """

    def __init__(self, params: List[Tensor]):
        """
        Initialize optimizer with parameters to optimize.

        TODO: Set up the parameter list for optimization

        APPROACH:
        1. Store parameters as a list for iteration
        2. Validate that all parameters require gradients
        3. Initialize step counter for algorithms that need it

        EXAMPLE:
        >>> linear = Linear(784, 128)
        >>> optimizer = SGD(linear.parameters(), lr=0.01)

        HINT: Store parameters for iteration during optimization steps
        """
        ### BEGIN SOLUTION
        if not isinstance(params, list):
            params = list(params)

        for param in params:
            if isinstance(param, Tensor):
                param.requires_grad = True
                param.grad = None
        
        self.params = params
        self.step_count = 0
        ### END SOLUTION

    def zero_grad(self):
        """
        Clear gradients from all parameters.

        TODO: Reset all parameter gradients to None

        APPROACH:
        1. Iterate through all parameters
        2. Set each parameter's grad to None

        EXAMPLE:
        >>> optimizer.zero_grad()  # Clears all gradients
        >>> assert param.grad is None for param in optimizer.params

        WHY: Gradients accumulate by default, so we need to clear them between batches
        """
        ### BEGIN SOLUTION
        for param in self.params:
            param.grad = None
        ### END SOLUTION

    def step(self):
        """
        Update parameters based on gradients.

        This is abstract - each optimizer implements its own update rule.
        """
        raise NotImplementedError(
            f"Abstract method step() not implemented\n"
            f"  ❌ {self.__class__.__name__} inherits from Optimizer but doesn't define step()\n"
            f"  💡 Each optimizer must implement its own update rule (SGD, Adam, etc.)\n"
            f"  🔧 Override step() in your optimizer subclass:\n"
            f"      def step(self):\n"
            f"          for param in self.params:\n"
            f"              if param.grad is not None:\n"
            f"                  param.data -= self.lr * param.grad.data"
        )

# %% ../../modules/07_optimizers/optimizers.ipynb #49e41a5d
class _ExtractGradientMixin:
    """Mixin added to Optimizer for gradient extraction."""
    def _extract_gradient(self, param: Tensor) -> np.ndarray:
        """
        Extract gradient data as a NumPy array from a parameter.

        Gradients can be stored as either a Tensor (with .data attribute)
        or as a raw NumPy array (from autograd). This helper normalizes
        both cases to a plain NumPy array for optimizer math.

        TODO: Return the gradient's underlying NumPy array

        APPROACH:
        1. Get param.grad
        2. If it's a Tensor, return its .data attribute
        3. If it's already a NumPy array, return it directly

        EXAMPLE:
        >>> param = Tensor([1.0, 2.0], requires_grad=True)
        >>> param.grad = Tensor([0.1, 0.2])
        >>> optimizer._extract_gradient(param)
        array([0.1, 0.2])

        HINT: Use isinstance(grad, Tensor) to check the type
        """
        ### BEGIN SOLUTION
        grad = param.grad
        if isinstance(grad, Tensor):
            return grad.data
        else:
            return np.asarray(grad)
        ### END SOLUTION

# Attach _extract_gradient to Optimizer so all subclasses inherit it
Optimizer._extract_gradient = _ExtractGradientMixin._extract_gradient

# %% ../../modules/07_optimizers/optimizers.ipynb #a43b1464
class SGD(Optimizer):
    """
    Stochastic Gradient Descent with momentum.

    SGD is the foundational optimization algorithm that moves parameters
    in the direction opposite to gradients. With momentum, it remembers
    previous updates to reduce oscillations and accelerate convergence.
    """

    def __init__(self, params: List[Tensor], lr: float = DEFAULT_LEARNING_RATE_SGD, momentum: float = 0.0, weight_decay: float = 0.0):
        """
        Initialize SGD optimizer.

        TODO: Set up SGD with momentum and weight decay

        APPROACH:
        1. Call parent constructor to set up parameters
        2. Store learning rate, momentum, and weight decay
        3. Initialize momentum buffers for each parameter

        EXAMPLE:
        >>> optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)

        HINTS:
        - Momentum buffers should be initialized as None
        - They'll be created lazily on first step
        """
        ### BEGIN SOLUTION
        super().__init__(params)
        
        self.lr = lr
        self.momentum = momentum
        self.weight_decay = weight_decay

        if momentum != 0:
            self.momentum_buffers = [None for _ in params]
        ### END SOLUTION

    def has_momentum(self) -> bool:
        """
        Check if this optimizer uses momentum.

        This explicit API method replaces the need for hasattr() checks
        in checkpointing code (Module 08).

        Returns:
            bool: True if momentum is enabled (momentum > 0), False otherwise

        EXAMPLE:
            >>> optimizer = SGD(params, lr=0.01, momentum=0.9)
            >>> optimizer.has_momentum()
            True
        """
        return self.momentum > 0

    def get_momentum_state(self) -> Optional[List]:
        """
        Get momentum buffers for checkpointing.

        This explicit API method provides safe access to momentum buffers
        without using hasattr(), making the API contract clear.

        Returns:
            Optional[List]: List of momentum buffers if momentum is enabled,
                          None otherwise

        EXAMPLE:
            >>> optimizer = SGD(params, lr=0.01, momentum=0.9)
            >>> optimizer.step()  # Initialize buffers
            >>> state = optimizer.get_momentum_state()
            >>> # Later: optimizer.set_momentum_state(state)
        """
        if not self.has_momentum():
            return None
        return [buf.copy() if buf is not None else None
                for buf in self.momentum_buffers]

    def set_momentum_state(self, state: Optional[List]) -> None:
        """
        Restore momentum buffers from checkpointing.

        This explicit API method provides safe restoration of momentum state
        without using hasattr().

        Args:
            state: List of momentum buffers or None

        EXAMPLE:
            >>> optimizer = SGD(params, lr=0.01, momentum=0.9)
            >>> state = optimizer.get_momentum_state()
            >>> # Training interruption...
            >>> new_optimizer = SGD(params, lr=0.01, momentum=0.9)
            >>> new_optimizer.set_momentum_state(state)
        """
        if state is None or not self.has_momentum():
            return

        if len(state) != len(self.momentum_buffers):
            raise ValueError(
                f"Momentum state length mismatch\n"
                f"  ❌ State has {len(state)} buffers, but optimizer has {len(self.momentum_buffers)} parameters\n"
                f"  💡 Checkpoint was saved with a different model architecture or parameter count\n"
                f"  🔧 Ensure you're loading state into an optimizer with the same number of parameters:\n"
                f"      # Check parameter counts match before restoring\n"
                f"      assert len(saved_state) == len(optimizer.params)"
            )

        for i, buf in enumerate(state):
            if buf is not None:
                self.momentum_buffers[i] = buf.copy()

    def step(self):
        """
        Perform SGD update step with momentum.

        TODO: Implement SGD parameter update by composing helpers

        APPROACH:
        1. For each parameter with gradients:
           a. Extract gradient using self._extract_gradient(param)
           b. Apply weight decay if specified
           c. Update momentum buffer
           d. Update parameter using momentum

        FORMULA:
        - With weight decay: grad = grad + weight_decay * param
        - Momentum: v = momentum * v_prev + grad
        - Update: param = param - lr * v

        HINTS:
        - Skip parameters without gradients
        - Use self._extract_gradient() from the base class
        - Initialize momentum buffers on first use
        """
        ### BEGIN SOLUTION
        for i, param in enumerate(self.params):
            if not isinstance(param, Tensor) or param.grad is None:
                continue
            
            grad_data = self._extract_gradient(param) # type: np.ndarray

            if self.weight_decay != 0:
                grad_data += self.weight_decay * param.data

            if self.momentum != 0:
                if self.momentum_buffers[i] is None:
                    self.momentum_buffers[i] = np.zeros_like(grad_data)
                self.momentum_buffers[i] = self.momentum * self.momentum_buffers[i] + grad_data
                grad_data = self.momentum_buffers[i]

            param.data -= self.lr * grad_data
            
        self.step_count += 1
        ### END SOLUTION

# %% ../../modules/07_optimizers/optimizers.ipynb #06ef697b
class Adam(Optimizer):
    """
    Adam optimizer with adaptive learning rates.

    Adam computes individual adaptive learning rates for different parameters
    from estimates of first and second moments of the gradients.
    This makes it effective for problems with sparse gradients or noisy data.
    """

    def __init__(self, params: List[Tensor], lr: float = DEFAULT_LEARNING_RATE_ADAM, betas: tuple = (DEFAULT_BETA1, DEFAULT_BETA2), eps: float = DEFAULT_EPS, weight_decay: float = 0.0):
        """
        Initialize Adam optimizer.

        TODO: Set up Adam with adaptive learning rates

        APPROACH:
        1. Call parent constructor
        2. Store hyperparameters (lr, betas, eps, weight_decay)
        3. Initialize first and second moment buffers

        PARAMETERS:
        - lr: Learning rate (default: 0.001)
        - betas: Coefficients for computing running averages (default: (0.9, 0.999))
        - eps: Small constant for numerical stability (default: 1e-8)
        - weight_decay: L2 penalty coefficient (default: 0.0)

        EXAMPLE:
        >>> optimizer = Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999))
        """
        ### BEGIN SOLUTION
        super().__init__(params)
        
        self.lr = lr
        self.beta1, self.beta2 = betas
        self.eps = eps
        self.weight_decay = weight_decay

        self.m_buffers = [None for _ in params]
        self.v_buffers = [None for _ in params]
        ### END SOLUTION

# %% ../../modules/07_optimizers/optimizers.ipynb #5f3a99ea
class _AdamUpdateMomentsMixin:
    """Mixin added to Adam for moment updates."""
    def _update_moments(self, i: int, grad_data: np.ndarray) -> tuple:
        """
        Update first and second moment estimates with bias correction.

        Computes the exponential moving averages of the gradient (first moment)
        and the squared gradient (second moment), then applies bias correction
        to counteract the zero-initialization bias in early training steps.

        TODO: Update moment buffers and return bias-corrected estimates

        APPROACH:
        1. Initialize m and v buffers to zeros if this is the first call
        2. Update first moment: m = beta1 * m + (1 - beta1) * grad
        3. Update second moment: v = beta2 * v + (1 - beta2) * grad^2
        4. Compute bias corrections using step_count
        5. Return bias-corrected m_hat and v_hat

        EXAMPLE:
        >>> m_hat, v_hat = self._update_moments(0, np.array([0.1, 0.2]))
        >>> # m_hat ≈ grad (after bias correction at step 1)
        >>> # v_hat ≈ grad^2 (after bias correction at step 1)

        HINTS:
        - Use self.step_count (already incremented before this call)
        - Bias correction denominators: (1 - beta^t) approach 1 as t grows
        """
        ### BEGIN SOLUTION
        if self.m_buffers[i] is None:
            self.m_buffers[i] = np.zeros_like(grad_data)
        if self.v_buffers[i] is None:
            self.v_buffers[i] = np.zeros_like(grad_data)
        
        self.m_buffers[i] = self.beta1 * self.m_buffers[i] + (1 - self.beta1) * grad_data
        self.v_buffers[i] = self.beta2 * self.v_buffers[i] + (1 - self.beta2) * grad_data ** 2

        bias_correction1 = 1.0 - self.beta1 ** self.step_count
        bias_correction2 = 1.0 - self.beta2 ** self.step_count
        
        m_hat = self.m_buffers[i] / bias_correction1
        v_hat = self.v_buffers[i] / bias_correction2

        return m_hat, v_hat
        ### END SOLUTION

# Attach _update_moments to Adam
Adam._update_moments = _AdamUpdateMomentsMixin._update_moments

# %% ../../modules/07_optimizers/optimizers.ipynb #146e2c6f
class _AdamStepMixin:
    """Mixin added to Adam for step method."""
    def step(self):
        """
        Perform Adam update step by composing helpers.

        TODO: Implement Adam parameter update using _extract_gradient and _update_moments

        APPROACH:
        1. Increment step_count (needed for bias correction)
        2. For each parameter with gradients:
           a. Extract gradient with self._extract_gradient(param)
           b. Apply weight decay to gradient if specified
           c. Update moments with self._update_moments(i, grad_data)
           d. Update parameter: param -= lr * m_hat / (sqrt(v_hat) + eps)

        FORMULAS:
        - θ_t = θ_{t-1} - lr * m̂_t / (√v̂_t + ε)

        HINTS:
        - Increment step_count FIRST (before the loop)
        - _update_moments returns (m_hat, v_hat) tuple
        - Weight decay modifies grad_data before moment update
        """
        ### BEGIN SOLUTION
        self.step_count += 1
        
        for i, param in enumerate(self.params):
            if not isinstance(param, Tensor) or param.grad is None:
                continue
            
            grad_data = self._extract_gradient(param) # type: np.ndarray

            if self.weight_decay != 0:
                grad_data += self.weight_decay * param.data

            m_hat, v_hat = self._update_moments(i, grad_data)

            param.data -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps)
        ### END SOLUTION

# Attach step to Adam
Adam.step = _AdamStepMixin.step

# %% ../../modules/07_optimizers/optimizers.ipynb #804dbcfa
class AdamW(Optimizer):
    """
    AdamW optimizer with decoupled weight decay.

    AdamW fixes a bug in Adam's weight decay implementation by decoupling
    weight decay from the gradient-based update. This leads to better
    regularization and is the preferred version for most applications.
    """

    def __init__(self, params: List[Tensor], lr: float = DEFAULT_LEARNING_RATE_ADAM, betas: tuple = (DEFAULT_BETA1, DEFAULT_BETA2), eps: float = DEFAULT_EPS, weight_decay: float = DEFAULT_WEIGHT_DECAY_ADAMW):
        """
        Initialize AdamW optimizer.

        TODO: Set up AdamW with decoupled weight decay

        APPROACH:
        1. Call parent constructor
        2. Store hyperparameters (note higher default weight_decay)
        3. Initialize moment buffers like Adam

        KEY DIFFERENCE from Adam:
        - Weight decay is applied directly to parameters, not added to gradients
        - This provides better regularization behavior

        EXAMPLE:
        >>> optimizer = AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
        """
        ### BEGIN SOLUTION
        super().__init__(params)
        
        self.lr = lr
        self.beta1, self.beta2 = betas
        self.eps = eps
        self.weight_decay = weight_decay

        self.m_buffers = [None for _ in params]
        self.v_buffers = [None for _ in params]
        ### END SOLUTION

# %% ../../modules/07_optimizers/optimizers.ipynb #8a3ab673
class _AdamWUpdateMomentsMixin:
    """Mixin added to AdamW for moment updates."""
    def _update_moments(self, i: int, grad_data: np.ndarray) -> tuple:
        """
        Update first and second moment estimates with bias correction for AdamW.

        Identical math to Adam's _update_moments: EMA of gradient and squared
        gradient, with bias correction. The key difference is in how step()
        calls this -- AdamW passes pure gradients without weight decay mixed in.

        TODO: Update moment buffers and return bias-corrected estimates

        APPROACH:
        1. Initialize m and v buffers to zeros if this is the first call
        2. Update first moment: m = beta1 * m + (1 - beta1) * grad
        3. Update second moment: v = beta2 * v + (1 - beta2) * grad^2
        4. Compute bias corrections using step_count
        5. Return bias-corrected m_hat and v_hat

        EXAMPLE:
        >>> m_hat, v_hat = self._update_moments(0, np.array([0.1, 0.2]))

        HINT: Same math as Adam -- the decoupling happens in step(), not here
        """
        ### BEGIN SOLUTION
        if self.m_buffers[i] is None:
            self.m_buffers[i] = np.zeros_like(grad_data)
        if self.v_buffers[i] is None:
            self.v_buffers[i] = np.zeros_like(grad_data)
        
        self.m_buffers[i] = self.beta1 * self.m_buffers[i] + (1 - self.beta1) * grad_data
        self.v_buffers[i] = self.beta2 * self.v_buffers[i] + (1 - self.beta2) * grad_data ** 2

        bias_correction1 = 1.0 - self.beta1 ** self.step_count
        bias_correction2 = 1.0 - self.beta2 ** self.step_count
        
        m_hat = self.m_buffers[i] / bias_correction1
        v_hat = self.v_buffers[i] / bias_correction2

        return m_hat, v_hat
        ### END SOLUTION

# Attach _update_moments to AdamW
AdamW._update_moments = _AdamWUpdateMomentsMixin._update_moments

# %% ../../modules/07_optimizers/optimizers.ipynb #52856713
class _AdamWStepMixin:
    """Mixin added to AdamW for step method."""
    def step(self):
        """
        Perform AdamW update step by composing helpers with decoupled weight decay.

        TODO: Implement AdamW parameter update using _extract_gradient and _update_moments

        APPROACH:
        1. Increment step_count (needed for bias correction)
        2. For each parameter with gradients:
           a. Extract gradient with self._extract_gradient(param)
           b. Update moments with self._update_moments(i, grad_data) -- pure gradient
           c. Apply gradient update: param -= lr * m_hat / (sqrt(v_hat) + eps)
           d. Apply weight decay separately: param *= (1 - lr * weight_decay)

        KEY DIFFERENCE from Adam:
        - NO weight decay added to gradient before moment update
        - Weight decay applied directly to parameter AFTER gradient update

        HINTS:
        - Do NOT modify grad_data with weight decay (that's Adam's bug)
        - Apply decay as a multiplicative factor on param.data
        """
        ### BEGIN SOLUTION
        self.step_count += 1
        
        for i, param in enumerate(self.params):
            if not isinstance(param, Tensor) or param.grad is None:
                continue
            
            grad_data = self._extract_gradient(param) # type: np.ndarray

            m_hat, v_hat = self._update_moments(i, grad_data)

            param.data -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps)
            
            if self.weight_decay != 0:
                param.data *= 1.0 - self.weight_decay
        ### END SOLUTION

# Attach step to AdamW
AdamW.step = _AdamWStepMixin.step
