# AUTOGENERATED! DO NOT EDIT! File to edit: ../../modules/08_training/training.ipynb.

# %% auto #0
__all__ = ['rng', 'DEFAULT_MAX_LR', 'DEFAULT_MIN_LR', 'DEFAULT_TOTAL_EPOCHS', 'CosineSchedule', 'clip_grad_norm', 'Trainer',
           'trainer_init', 'trainer_train_epoch', 'trainer_evaluate', 'trainer_save_checkpoint',
           'trainer_load_checkpoint']

# %% ../../modules/08_training/training.ipynb #441a1371
import numpy as np
rng = np.random.default_rng(42)
import pickle
import time
from typing import Dict, List, Optional, Tuple, Any, Callable
from pathlib import Path
import sys
import os

# Import dependencies from other modules
from .tensor import Tensor
from .layers import Linear
from .losses import MSELoss, CrossEntropyLoss
from .optimizers import SGD, AdamW

# Enable autograd for gradient tracking (required for training)
from .autograd import enable_autograd
enable_autograd()

# Constants for learning rate scheduling defaults
DEFAULT_MAX_LR = 0.1  # Default maximum learning rate for cosine schedule
DEFAULT_MIN_LR = 0.01  # Default minimum learning rate for cosine schedule
DEFAULT_TOTAL_EPOCHS = 100  # Default total epochs for learning rate schedule

# %% ../../modules/08_training/training.ipynb #dd2a12b2
class CosineSchedule:
    """
    Cosine annealing learning rate schedule.

    Starts at max_lr, decreases following a cosine curve to min_lr over T epochs.
    This provides aggressive learning initially, then fine-tuning at the end.

    TODO: Implement cosine annealing schedule

    APPROACH:
    1. Store max_lr, min_lr, and total_epochs
    2. In get_lr(), compute cosine factor: (1 + cos(π * epoch / total_epochs)) / 2
    3. Interpolate: min_lr + (max_lr - min_lr) * cosine_factor

    EXAMPLE:
    >>> schedule = CosineSchedule(max_lr=0.1, min_lr=0.01, total_epochs=100)
    >>> print(schedule.get_lr(0))    # Start: 0.1
    >>> print(schedule.get_lr(50))   # Middle: ~0.055
    >>> print(schedule.get_lr(100))  # End: 0.01

    HINT: Use np.cos() and np.pi for the cosine calculation
    """
    ### BEGIN SOLUTION
    def __init__(self, max_lr, min_lr, total_epochs):
        self.max_lr = max_lr
        self.min_lr = min_lr
        self.total_epochs = total_epochs

    def get_lr(self, epoch):
        cosine_factor = (1.0 + np.cos(np.pi * epoch / self.total_epochs)) * 0.5
        lr = self.min_lr + (self.max_lr - self.min_lr) * cosine_factor
        return lr
    ### END SOLUTION

# %% ../../modules/08_training/training.ipynb #c8f388e3
def clip_grad_norm(parameters: List, max_norm: float = 1.0) -> float:
    """
    Clip gradients by global norm to prevent exploding gradients.

    This is crucial for training stability, especially with RNNs and deep networks.
    Instead of clipping each gradient individually, we compute the global norm
    across all parameters and scale uniformly if needed.

    TODO: Implement gradient clipping by global norm

    APPROACH:
    1. Compute total norm: sqrt(sum of squared gradients across all parameters)
    2. If total_norm > max_norm, compute clip_coef = max_norm / total_norm
    3. Scale all gradients by clip_coef: grad *= clip_coef
    4. Return the original norm for monitoring

    EXAMPLE:
    >>> params = [Tensor([1, 2, 3], requires_grad=True)]
    >>> params[0].grad = Tensor([10, 20, 30])  # Large gradients
    >>> original_norm = clip_grad_norm(params, max_norm=1.0)
    >>> print(f"Clipped norm: {np.linalg.norm(params[0].grad.data):.2f}")  # Should be ≤ 1.0

    HINTS:
    - Use np.linalg.norm() to compute norms
    - Only clip if total_norm > max_norm
    - Modify gradients in-place for efficiency
    """
    ### BEGIN SOLUTION
    total_norm = 0
    for param in parameters:
        if param.grad is not None:
            total_norm += np.sum(param.grad ** 2)

    total_norm = np.sqrt(total_norm)
    
    if total_norm > max_norm:
        clip_coef = max_norm / total_norm
        for param in parameters:
            if param.grad is not None:
                param.grad *= clip_coef

    return total_norm
    ### END SOLUTION

# %% ../../modules/08_training/training.ipynb #25bb94eb
class Trainer:
    """
    Complete training orchestrator for neural networks.

    Handles the full training lifecycle: forward pass, loss computation,
    backward pass, optimization, scheduling, checkpointing, and evaluation.

    This is the central class that brings together all the components
    you've built in previous modules.
    """

    # ── Private serialization helpers (provided, not student-implemented) ──
    # These are pickle plumbing for checkpoint save/load. The training
    # concepts you'll implement are in the public methods below.

    def _get_model_state(self):
        """Extract model parameters for checkpointing."""
        return {i: param.data.copy() for i, param in enumerate(self.model.parameters())}

    def _set_model_state(self, state):
        """Restore model parameters from checkpoint."""
        for i, param in enumerate(self.model.parameters()):
            if i in state:
                param.data = state[i].copy()

    def _get_optimizer_state(self):
        """Extract optimizer state for checkpointing."""
        state = {}
        state['lr'] = self.optimizer.lr
        if hasattr(self.optimizer, 'has_momentum') and self.optimizer.has_momentum():
            momentum_state = self.optimizer.get_momentum_state()
            if momentum_state is not None:
                state['momentum_buffers'] = momentum_state
        return state

    def _set_optimizer_state(self, state):
        """Restore optimizer state from checkpoint."""
        if 'lr' in state:
            self.optimizer.lr = state['lr']
        if 'momentum_buffers' in state:
            if hasattr(self.optimizer, 'has_momentum') and self.optimizer.has_momentum():
                self.optimizer.set_momentum_state(state['momentum_buffers'])

    def _get_scheduler_state(self):
        """Extract scheduler state for checkpointing."""
        if self.scheduler is None:
            return None
        return {
            'max_lr': getattr(self.scheduler, 'max_lr', None),
            'min_lr': getattr(self.scheduler, 'min_lr', None),
            'total_epochs': getattr(self.scheduler, 'total_epochs', None)
        }

    def _set_scheduler_state(self, state):
        """Restore scheduler state from checkpoint."""
        if state is None or self.scheduler is None:
            return
        for key, value in state.items():
            if hasattr(self.scheduler, key):
                setattr(self.scheduler, key, value)

# %% ../../modules/08_training/training.ipynb #3a8b6421
def trainer_init(self, model, optimizer, loss_fn, scheduler=None, grad_clip_norm=None):
    """
    Initialize trainer with model and training components.

    Args:
        model: Neural network to train (must have .forward() and .parameters())
        optimizer: Parameter update strategy (SGD, Adam, etc.)
        loss_fn: Loss function (CrossEntropy, MSE, etc.)
        scheduler: Optional learning rate scheduler (e.g., CosineSchedule)
        grad_clip_norm: Optional max gradient norm for clipping (float)

    TODO: Store all components and initialize training state

    APPROACH:
    1. Store model, optimizer, loss_fn, scheduler, and grad_clip_norm as attributes
    2. Enable gradient tracking: set requires_grad=True on all model.parameters()
    3. Initialize epoch=0, step=0, training_mode=True
    4. Create history dict with keys: 'train_loss', 'eval_loss', 'learning_rates'
       (each mapping to an empty list)

    EXAMPLE:
    >>> trainer = Trainer(model, optimizer, MSELoss())
    >>> print(trainer.epoch)     # 0
    >>> print(trainer.step)      # 0
    >>> print(trainer.history)   # {'train_loss': [], 'eval_loss': [], 'learning_rates': []}

    HINT: This is straightforward assignment. The key insight is WHAT state
    a training system needs to track across epochs.
    """
    ### BEGIN SOLUTION
    self.model = model
    self.optimizer = optimizer
    self.loss_fn = loss_fn
    self.scheduler = scheduler
    self.grad_clip_norm = grad_clip_norm

    for param in model.parameters():
        param.requires_grad = True

    self.epoch = 0
    self.step = 0
    self.training_mode = True

    self.history = {
        'train_loss': [], 
        'eval_loss': [], 
        'learning_rates': []
    }
    ### END SOLUTION

Trainer.__init__ = trainer_init

# %% ../../modules/08_training/training.ipynb #886eab47
def _trainer_process_batch(self, inputs, targets, accumulation_steps):
    """
    Process one batch: forward pass, loss computation, backward pass.

    Args:
        inputs: Input tensor for this batch
        targets: Target tensor for this batch
        accumulation_steps: Number of batches per optimizer update (for scaling)

    Returns:
        Scaled loss value (float) for accumulation tracking

    TODO: Implement the forward-backward cycle for a single batch

    APPROACH:
    1. Forward pass: model.forward(inputs)
    2. Compute loss: loss_fn.forward(outputs, targets)
    3. Scale loss by 1/accumulation_steps
    4. Backward pass with scaled gradient

    HINT: scaled_gradient = np.ones_like(loss.data) / accumulation_steps
    """
    ### BEGIN SOLUTION
    outputs = self.model.forward(inputs)
    loss = self.loss_fn.forward(outputs, targets)
    loss.backward()

    scaled_loss = loss / accumulation_steps
    return float(scaled_loss.data)
    ### END SOLUTION

Trainer._process_batch = _trainer_process_batch

# %% ../../modules/08_training/training.ipynb #4f7ee97d
def _trainer_optimizer_update(self):
    """
    Clip gradients (if enabled) and step the optimizer.

    TODO: Implement the gradient clip + optimizer step + zero_grad cycle

    APPROACH:
    1. If grad_clip_norm is set, call clip_grad_norm on model parameters
    2. Call optimizer.step() to update weights
    3. Call optimizer.zero_grad() to reset gradients
    """
    ### BEGIN SOLUTION
    if self.grad_clip_norm is not None:
        params = self.model.parameters()
        clip_grad_norm(params, self.grad_clip_norm)
    
    self.optimizer.step()
    self.optimizer.zero_grad()
    ### END SOLUTION

Trainer._optimizer_update = _trainer_optimizer_update

# %% ../../modules/08_training/training.ipynb #db724748
def trainer_train_epoch(self, dataloader, accumulation_steps=1):
    """
    Train for one epoch through the dataset.

    Args:
        dataloader: Iterable yielding (inputs, targets) batches
        accumulation_steps: Number of batches to accumulate before update

    Returns:
        Average loss for the epoch (float)

    TODO: Compose _process_batch and _optimizer_update into the epoch loop

    APPROACH:
    1. Set model.training = True and self.training_mode = True
    2. Loop over batches, calling self._process_batch for each
    3. Every accumulation_steps batches, call self._optimizer_update
    4. Handle remaining accumulated gradients after the loop
    5. Record average loss, update scheduler, increment epoch

    HINT: Check (batch_idx + 1) % accumulation_steps == 0 for update timing
    """
    ### BEGIN SOLUTION
    self.model.training = True
    self.training_mode = True

    total_loss = 0.0
    accumulated_loss = 0.0
    num_batchs = 0

    for batch_idx, (inputs, targets) in enumerate(dataloader):
        scaled_loss = self._process_batch(inputs, targets, accumulation_steps)
        accumulated_loss += scaled_loss
        
        if (batch_idx + 1) % accumulation_steps == 0:
            self._optimizer_update()
            
            total_loss += accumulated_loss
            accumulated_loss = 0.0
            self.step += 1
            num_batchs += 1

    if accumulated_loss > 0:
        self._optimizer_update()

        total_loss += accumulated_loss
        self.step += 1
    
    average_loss = total_loss / max(num_batchs, 1)
    self.history['train_loss'].append(average_loss)

    if self.scheduler is not None:
        lr = self.scheduler.get_lr(self.epoch)
        self.optimizer.lr = lr
        self.history['learning_rates'].append(lr)

    self.epoch += 1

    return average_loss
    ### END SOLUTION

Trainer.train_epoch = trainer_train_epoch

# %% ../../modules/08_training/training.ipynb #b12d5f33
def trainer_evaluate(self, dataloader):
    """
    Evaluate model on dataset without updating parameters.

    Args:
        dataloader: Iterable yielding (inputs, targets) batches

    Returns:
        Tuple of (average_loss, accuracy)

    TODO: Implement evaluation loop (forward pass only, no gradient updates)

    APPROACH:
    1. Set model.training = False and self.training_mode = False
    2. For each batch: forward pass only, accumulate loss
    3. For classification: compute accuracy from argmax predictions
    4. Record average loss in self.history['eval_loss']
    5. Return (avg_loss, accuracy)

    EXAMPLE:
    >>> eval_loss, accuracy = trainer.evaluate(test_data)
    >>> print(f"Eval loss: {eval_loss:.4f}, Accuracy: {accuracy:.2%}")

    HINTS:
    - For multi-class: predictions = np.argmax(outputs.data, axis=1)
    - Handle both integer targets and one-hot targets
    - accuracy = correct / total if total > 0 else 0.0
    """
    ### BEGIN SOLUTION
    self.model.training = False
    self.training_mode = False

    total_loss = 0.0
    correct = 0
    total = 0

    for inputs, targets in dataloader:
        outputs = self.model.forward(inputs)
        loss = self.loss_fn.forward(outputs, targets)
        
        total_loss += loss.data

        if outputs.ndim > 1 and outputs.shape[-1] > 1: # multi-class
            predictions = np.argmax(outputs.data, axis=1)
            total += len(predictions)
            
            if targets.ndim == 1: # integer targets
                correct += np.sum(predictions == targets.data)
            else: # one-hot targets
                correct += np.sum(predictions == np.argmax(targets.data, axis=1))
    
    average_loss = total_loss / total if total > 0 else 0.0
    accuracy = correct / total if total > 0 else 0.0

    self.history['eval_loss'].append(average_loss)

    return average_loss, accuracy
    ### END SOLUTION

Trainer.evaluate = trainer_evaluate

# %% ../../modules/08_training/training.ipynb #da17a488
def trainer_save_checkpoint(self, path: str):
    """
    Save complete training state for resumption.

    Args:
        path: File path to save checkpoint (.pkl)

    TODO: Serialize all training state to disk using pickle

    APPROACH:
    1. Build a checkpoint dict with keys: epoch, step, model_state,
       optimizer_state, scheduler_state, history, training_mode
    2. Use self._get_model_state(), self._get_optimizer_state(),
       self._get_scheduler_state() to extract component states
    3. Create parent directory if needed: Path(path).parent.mkdir(parents=True, exist_ok=True)
    4. Write with pickle.dump()

    EXAMPLE:
    >>> trainer.save_checkpoint('/tmp/checkpoint.pkl')
    >>> # Later: trainer.load_checkpoint('/tmp/checkpoint.pkl')

    HINT: The private _get_*_state() helpers are already provided.
    """
    ### BEGIN SOLUTION
    checkpoint = {
        'epoch': self.epoch,
        'step': self.step,
        'model_state': self._get_model_state(),
        'optimizer_state': self._get_optimizer_state(),
        'scheduler_state': self._get_scheduler_state(),
        'history': self.history,
        'training_mode': self.training_mode
    }

    Path(path).parent.mkdir(parents=True, exist_ok=True)

    with open(path, "wb") as f:
        pickle.dump(checkpoint, f)
    ### END SOLUTION

Trainer.save_checkpoint = trainer_save_checkpoint

# %% ../../modules/08_training/training.ipynb #2e7b478b
def trainer_load_checkpoint(self, path: str):
    """
    Load training state from checkpoint.

    Args:
        path: File path to load checkpoint from (.pkl)

    TODO: Deserialize training state from disk and restore all components

    APPROACH:
    1. Open and unpickle the checkpoint file
    2. Restore self.epoch, self.step, self.history, self.training_mode
    3. Call self._set_model_state() if 'model_state' in checkpoint
    4. Call self._set_optimizer_state() if 'optimizer_state' in checkpoint
    5. Call self._set_scheduler_state() if 'scheduler_state' in checkpoint

    EXAMPLE:
    >>> trainer.save_checkpoint('/tmp/checkpoint.pkl')
    >>> trainer.epoch = 999  # Some change
    >>> trainer.load_checkpoint('/tmp/checkpoint.pkl')
    >>> print(trainer.epoch)  # Restored to original value

    HINT: The private _set_*_state() helpers are already provided.
    """
    ### BEGIN SOLUTION
    with open(path, "rb") as f:
        checkpoint = pickle.load(f)

    self.epoch = checkpoint['epoch']
    self.step = checkpoint['step']
    self.history = checkpoint['history']
    self.training_mode = checkpoint['training_mode']

    if 'model_state' in checkpoint:
        self._set_model_state(checkpoint['model_state'])
    if 'optimizer_state' in checkpoint:
        self._set_optimizer_state(checkpoint['optimizer_state'])
    if 'scheduler_state' in checkpoint:
        self._set_scheduler_state(checkpoint['scheduler_state'])
    ### END SOLUTION

Trainer.load_checkpoint = trainer_load_checkpoint
